version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Docker/Flask/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./WebApp:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development

